### PR TITLE
296 config file not correct

### LINKED ISSUE #296: Database configuration won't be written to config.php file
Hello @stephenlawrence 
I've the same problem. I've put ODM on my webspace and started the installation. I've put the credentials for the database into the fields but it wouldn't write to the config file. The next step brings the message "Error!: SQLSTATE[28000] [1045] Access denied for user 'opendocman'@'localhost' (using password: YES) - Please make sure you have created a database" the DB is created. In the message are not the correct user, DB-Name and  the ODM-Folder ist writeble and the config.php-file too. When I put the credentals manually into the config file I'll get the CSRF message.

Hope you can help!
Stephen

_Originally posted by @DerKaffeeschluerfer in https://github.com/opendocman/opendocman/issues/291#issuecomment-772559260_

### PR DESCRIPTION
**Pull request by stephenlawrence**
Fixes #296

### CODE REVIEW

**Comment by DerKaffeeschluerfer** [comment]
A complete new try. New git clone, new database. Configuration form is ok, the database has been generated. After the first login I got this white page.
grafik

____

When I try a new login I get this white page.

grafik

**Comment by stephenlawrence** [comment]
@DerKaffeeschluerfer Any way you can enable error logs? 

Can you add this to the code?:
```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

**Comment by DerKaffeeschluerfer** [comment]
> Can you add this to the code?:

In which file?

**Comment by stephenlawrence** [comment]
You can add it to the top of out.php to start with, assuming your getting a login page OK.

**Comment by DerKaffeeschluerfer** [comment]
Here is the output:
`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Smarty has a deprecated constructor in /hp/bv/ab/gd/www/doc/includes/smarty/Smarty.class.php on line 64

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; User has a deprecated constructor in /hp/bv/ab/gd/www/doc/User_class.php on line 25

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; User_Perms has a deprecated constructor in /hp/bv/ab/gd/www/doc/User_Perms_class.php on line 24

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; UserPermission has a deprecated constructor in /hp/bv/ab/gd/www/doc/UserPermission_class.php on line 24

Fatal error: Uncaught Error: Call to undefined method databaseData::databaseData() in /hp/bv/ab/gd/www/doc/User_class.php:52 Stack trace: #0 /hp/bv/ab/gd/www/doc/functions.php(121): User->User('1', Object(PDO)) #1 /hp/bv/ab/gd/www/doc/out.php(44): draw_header('Files List', '') #2 {main} thrown in /hp/bv/ab/gd/www/doc/User_class.php on line 52`

**Comment by stephenlawrence** [comment]
Which PHP version is being used?

**Comment by DerKaffeeschluerfer** [comment]
7.3.23

**Comment by DerKaffeeschluerfer** [comment]
I can go to 7.0, 7.1, 7.2, 7.3, 7.4

**Comment by stephenlawrence** [comment]
This issue was also reported by another user via #301 . I have since pushed 1.4.1 release to master branch that should resolve this.

**Comment by DerKaffeeschluerfer** [comment]
I'll try it

**Comment by DerKaffeeschluerfer** [comment]
Wow! It works! Thanks a lot for your great support!

**Comment by stephenlawrence** [comment]
Awesome! Sorry for all the back and forth. I have not been working on the project much the past couple years so I had to fix everything broken since then. :)

**Comment by DerKaffeeschluerfer** [comment]
Very cool! I like to do troubleshooting on IT stuff ;-) 

I'm not going to ask what's happen when I change PHP to 7.4 :-D

I've just seen that the admin page shows the version of the database is 1.3.6 but the installation wizzard says that the database version 1.4.0 has been generated

**Comment by stephenlawrence** [comment]
@DerKaffeeschluerfer Does /install/ show you upgrade options? There was a small change to the database schema in 1.4.0 that would require an upgrade if you are still pointed at an existing mysql database.

**Comment by DerKaffeeschluerfer** [comment]
No, I started with a fresh install with an emty database. The installer says that version 1.4 will be installed. On the admin page is it version 1.3.6

**Pull request merged**
